# Generated by Django 3.2.15 on 2022-10-19 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0162_signal_user_HISTORY'),
    ]

    operations = [
        migrations.CreateModel(
            name='Melding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msb_id', models.PositiveBigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signals.signal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
