# Generated by Django 3.2.15 on 2022-10-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='melding',
            name='msb_item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='melding',
            name='msb_list_item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='melding',
            name='msb_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
