name: Manually build a Docker image for a given tag and push to Docker hub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to build and push an image for
        required: true

jobs:
  build_and_push:
    name: Build a new Docker image for the given tag and push it to Docker
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: mguikema/signalen-backend:latest
